"""Memory tools registry. Each tool exports a callable + DESCRIPTION + INPUT_SCHEMA."""
from __future__ import annotations

from backend.memory.tools import (
    close_open_loop,
    connect_integration,
    list_calendar,
    list_gmail_recent,
    list_observations,
    list_open_loops,
    list_rules,
    log_observation,
    read_gmail_thread,
    read_situation_brief,
    recall_chat_thread,
    recall_document_chunks,
    recall_episodic,
    recall_graph,
    refresh_situation_brief,
    resolve_time_expression,
    schedule_reminder,
    smart_recall,
    set_timezone,
    track_open_loop,
    update_living_profile,
)

ALL_TOOLS = {
    "recall_episodic": recall_episodic,
    "recall_graph": recall_graph,
    "recall_document_chunks": recall_document_chunks,
    "recall_chat_thread": recall_chat_thread,
    "list_observations": list_observations,
    "list_open_loops": list_open_loops,
    "list_rules": list_rules,
    "list_calendar": list_calendar,
    "list_gmail_recent": list_gmail_recent,
    "read_gmail_thread": read_gmail_thread,
    "read_situation_brief": read_situation_brief,
    "smart_recall": smart_recall,
    "log_observation": log_observation,
    "track_open_loop": track_open_loop,
    "close_open_loop": close_open_loop,
    "set_timezone": set_timezone,
    "schedule_reminder": schedule_reminder,
    "refresh_situation_brief": refresh_situation_brief,
    "resolve_time_expression": resolve_time_expression,
    "update_living_profile": update_living_profile,
    "connect_integration": connect_integration,
}
